project:
  type: book
  resources:
  - webr-serviceworker.js
  - webr-worker.js
  - coi-serviceworker.js
book:
  title: A tutorial to support multivariate Bayesian analyses in nursing research
  author: Lacey W. Heinsberg, PhD, RN 
  date: today
  date-format: long
  chapters:
  - index.qmd
  - intro.qmd 
  - prep.qmd
  - bnlearn.qmd
  - mvbimbam.qmd
  appendices:
  - Troubleshooting.qmd  
  - InstallationHack.qmd
format:
  html:
    theme: cosmo
    css: include/webex.css
    include-after-body: include/webex.js
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/lwheinsberg\.github\.io\/mvNUR'
editor: visual
filters: 
  - webr
