# Preface {.unnumbered}

## About

This is a Quarto book created from markdown and executable code using Quarto within RStudio.

The goal of this book is to provide detailed code and a fully synthetic example data set to guide nurse scientists and other researchers in conducting multivariate Bayesian analyses to examine associations between correlated phenotypes and single nucleotide polymorphisms (SNPs, i.e., genetic variants).

Note that this content is available as a website (which you are currently reading) or as a [GitHub repository](https://github.com/lwheinsberg/mvNUR) (where all code can be downloaded/edited).

Book web site: <https://lwheinsberg.github.io/mvNUR/>

GitHub repository: <https://github.com/lwheinsberg/mvNUR>

Book source code: <https://github.com/lwheinsberg/mvNUR/tree/gh-pages>

## Author

Lacey W. Heinsberg, PhD, RN: law145\@pitt.edu

If you have any questions or comments, please feel free to contact me!

## Copyright

Copyright information:

Copyright 2023, University of Pittsburgh. All Rights Reserved. License: [GPL-2](https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html)

## More information

-   To learn more about Quarto books visit: <https://quarto.org/docs/books/>.
-   R/Unix basics:
    -   <https://danieleweeks.github.io/HuGen2071/preparation.html>
    -   <https://github.com/ajwills72/rminr>
    -   <https://www.andywills.info/rminr/#beginners>
    -   <https://www.youtube.com/watch?v=IrDUcdpPmdI>
-   Bayesian power calculations
    -   <https://www.andywills.info/rminr/power-bayesian.html>
    -   <https://solomonkurz.netlify.app/blog/bayesian-power-analysis-part-i/>
    - 	<https://cran.r-project.org/web/packages/BayesianPower/vignettes/bayesianpower.html>
-   Other Bayesian software 
    - [BayesSUR](https://github.com/mbant/BayesSUR)
    - [tan](https://pgmpy.org/examples/Structure%20Learning%20with%20TAN.html)
    - [jags](https://mcmc-jags.sourceforge.io/)
    - [brms](https://paul-buerkner.github.io/brms/)
    - [blavaan](https://ecmerkle.github.io/blavaan/)
    - [bayesian_first_aid](https://github.com/rasmusab/bayesian_first_aid)

## Acknowledgments

Please note that this book was created from content presented at the International Society of Nurses in Genetics:

*Heinsberg LW. Multivariate Bayesian Approaches for Analyzing Correlated Phenotypes in Nursing Research. (Expert Lecturer Abstract, Podium). Presented at the International Society of Nurses in Genetics, November 2023, Providence, Rhode Island*

which has been adapted for (hopeful) publication as a manuscript entitled:

*Heinsberg LW, Davis TS, Maher D, Bender CM, Conley YP, Weeks DE. A Guide to Multivariate Bayesian Analyses in Nursing Research. Submitted to Biological Research for Nursing.*

I'd also like to express my gratitude to the following for their support and contributions to this repository:

-   Support from the National Institutes of Health under award number K99HD107030 made this project possible, and for that, I'm truly grateful.

-   Special thanks to Dr. Tara Davis and Mr. Dylan Maher for being "test users" and providing their feedback on this guide.

-   My deepest gratitude to Dr. Daniel Weeks. Without his guidance and inspiration, I would never have ventured into the world of Bayesian statistics, or pursued many other endeavors I once thought were beyond my capabilities.

*I have a Bayesian inference joke but the first three people I told it to didn't laugh and now I'm not so sure it's funny.* - **JSEllenberg**.
