---
title: "mvBIMBAM Installation Troubleshooting (Check for GSL)"
author: "Lacey W. Heinsberg"
output:
  github_document:
  html_preview: false
  toc: true
  pdf_document:
    toc: yes
    number_sections: true
    toc_depth: '5'
  html_document:
    df_print: paged
    toc: yes
    number_sections: true
    toc_depth: '5'
header-includes: 
  - \renewcommand{\and}{\\}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  #fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# Copyright information

Copyright 2024, University of Pittsburgh. All Rights Reserved. License: [GPL-2](https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html)

# Troubleshooting mvBIMBAM installation

To install mvBIMBAM, you'll need to use command line tools, which are programs that let you interact with your computer through text commands rather than clicking on icons. Think of it like giving your computer written instructions. You will also need to have GSL (GNU Scientific Library) installed on your machine. GSL is a free library that provides many useful mathematical and statistical functions for scientific computing. If you run into trouble installing mvBIMBAM, it’s often because GSL is not installed.

Once you have command line tools installed, you can use your terminal to see if you have GSL installed on your machine by asking for the version number:

```         
gsl-config --version
```

For example, on my machine, this command returns "2.7.1".

If GSL is not installed, some installation instructions are below.

## Mac / Linux

For Mac/Linux, the simplest way to install GSL is via homebrew. First, install homebrew following the instructions available at their website: <https://docs.brew.sh/Installation>.

To confirm that it has been installed, and check for the path:

```         
brew --version
brew --prefix
```

For example, on my machine, the first command returns "Homebrew 4.0.23" and the second returns "/opt/homebrew", though this could vary based on the type of machine you are working on.

Now let's move on to installing GSL:

```         
brew install gsl
```

Confirm install and path:

```         
gsl-config --version 
gsl-config --prefix
```

Voila! (Hopefully :))

## Windows

To install GSL for windows, you can follow the instructions available here: <https://gnuwin32.sourceforge.net/packages/gsl.htm> or <https://www.gnu.org/software/gsl/extras/native_win_builds.html>

Please move back to the installation instructions in the README file and try again!

# Contact information

If you have any questions or comments, please feel free to contact me!

Lacey W. Heinsberg, PhD, RN: [law145\@pitt.edu](mailto:law145@pitt.edu){.email}
